# Server
server:
  host: localhost:8080

# Logger
logging:
  level:
    "[xyz.cupscoffee]": DEBUG

  pattern:
    dateformat: HH:mm:ss
    console:
      "%clr(%d{HH:mm:ss}){faint} %highlight(%-5level) ---
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"

# Hikari
spring:
  datasource:
    url: jdbc:mysql://ba1ofnicch0ubxhay0f5-mysql.services.clever-cloud.com:3306/ba1ofnicch0ubxhay0f5
    username: uangjpuci8ogiw2r
    password: 0csCVNdmnA5pRmWy9kX3

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 3
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 60000
      auto-commit: true

  jpa:
    show-sql: true

    properties:
      hibernate:
        "[format_sql]": true

# Swagger
springdoc:
  api-docs:
    server-url: http://${server.host}${server.servlet.context-path}
