# Application
spring:
  config:
    import:
      - optional:classpath:.env[.properties]

  application:
    name: vet-manager-hc

  mvc:
    servlet:
      path: /api/${spring.api.version}

  api:
    version: v0

  profiles:
    active:
      - test

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    properties:
      "[org.hibernate.envers.audit_table_suffix]": _log

  image:
    path: /images

# Security
security:
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language

  allowed-public-routes:
    # Api
    - /health
    - /image/**
    - /external-dependencies
    - /auth/login
    # Swagger
    - /docs
    - /swagger-ui*/**
    - /v3/api-docs*/**

  allowed-origins:
    - "*"

  allowed-credentials: false

  jwt:
    secret: ${JWT_SECRET}

# Swagger
springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: alpha
    tagsSorter: alpha
