name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-distribution: "temurin"
          java-version: "21"

      - name: Kill the previous api process if exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            fuser -k 8080/tcp || echo "No process running on port 8080"

      - name: Install dependencies and build
        run: mvn install package -DskipTests

      - name: Create the folder api.vet-manager-hc
        run: mkdir api.vet-manager-hc

      - name: Move jar to api.vet-manager-hc
        run: mv target/*.jar api.vet-manager-hc

      - name: Copy the api.vet-manager-hc to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: api.vet-manager-hc
          target: /home/${{ secrets.USER }}

      - name: Ejecutamos la actualización de la api
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.USER }}/api.vet-manager-hc
            nohup java -jar *.jar \
                --spring.profiles.active=prod \
                --spring.datasource.url=${{ secrets.DB_URL }} \
                --spring.datasource.username=${{ secrets.DB_USERNAME }} \
                --spring.datasource.password=${{ secrets.DB_PASSWORD }} \
                > output.log 2>&1 &
