name: Deploy API to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Kill the previous api process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo fuser -k 8080/tcp || echo "No process running on port 8080"
            rm -rf /home/${{ secrets.USER }}/api.vet-manager-hc

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy the code to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: .
          target: /home/${{ secrets.USER }}/api.vet-manager-hc

      - name: Run the api
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.USER }}/api.vet-manager-hc
            chmod -R 755 ./mvnw
            chmod -R 755 ./config-server
            nohup bash -c 'cd /home/${{ secrets.USER }}/api.vet-manager-hc && \
                ./mvnw clean install -Pproduction && \
                ./config-server ${{ secrets.ADMIN_USERNAME }} ${{ secrets.ADMIN_PASSWORD }} ${{ secrets.DB_URL }} ${{ secrets.DB_USERNAME }} ${{ secrets.DB_PASSWORD }} && \
                ./mvnw wildfly:run -Pproduction' \
                > output.log 2>&1 &
